### ISSUE TITLE
Feature request: Create domain on nameserver

### ISSUE THREAD

**Issue by kimdre** [inwx/terraform-provider-inwx#18]
It seems you can't add a domain entry on a nameserver directly with the terraform provider, at least it was only possible for me to add dns entries when I add the domain manually in the web UI first.

The `inwx_domain` resource is only useful if the specified domain isn't in use yet and available for registration.

Would it be possible to add a new resource to do this?
This would be especially useful if you e.g. want to create/prepare dns entries before a domain transfer to INWX.
At the moment you need to create the domain manually before being able to use the `inwx_nameserver_record` resource at Nameserver > Nameserver entries

**Comment by 2martens** [comment]
I have been able to import the existing domain into a inwx_domain record but didn't try creating the domain that way.

**Comment by kimdre** [comment]
Yes, you could go to the web UI to create a domain entry on the nameserver for your external domain and then import it into your terraform state, but that's not really a good way to do that in my opinion.

**Comment by 2martens** [comment]
Absolutely. I am currently working on building my own platform and as part of that it would be cool to first fetch with the ordinary API if a domain is available and if so add it to the terraform repo and let terraform claim it. 

If the normal Domainrobot API can do it, why is the terraform provider not able to do it?

**Comment by 2martens** [comment]
Maybe a stupid question but how does the addition of an additional resource type solve this problem?

**Comment by kimdre** [comment]
You can create zones with this ressource without having to go to the web ui and you can also reference that ressource in the `domain` field for `inwx_nameserver_record`.
