### ISSUE TITLE
Feature request: Enable automated DNSSEC management for a domain

### ISSUE THREAD

**Issue by kimdre** [inwx/terraform-provider-inwx#19]
I would like to propse a new resource, that let's you enable the automated DNSSEC management for domains at INWX, as described in the API docs at 2.8.4 and 2.8.5: https://www.inwx.com/en/help/apidoc/f/ch02s08.html

**Comment by fsoederhuyzen** [comment]
This is already possible with the [inwx_dnssec_key](https://github.com/inwx/terraform-provider-inwx/blob/main/docs/resources/inwx_dnssec_key.md) resource.

**Comment by kimdre** [comment]
@fsoederhuyzen Does this really work with automated DNSSEC key generation?
I have no clue what to enter in the required arguments for `public_key ` and `algorithm `, as I don't generate DNSSEC keys myself. I always to this just be enabling the checkbox in the INWX UI.

**Comment by fsoederhuyzen** [comment]
@kimdre youre right this is still missing, ive overread "automatic".
