### ISSUE TITLE
Feature request: Read configuration from environment

### ISSUE THREAD

**Issue by lkubb** [inwx/terraform-provider-inwx#22]
Currently, the provider configuration can only be passed in by specifying it as part of the state. This causes sensitive data to be written to `tfstate`.

Many providers can be configured via specific environment variables in order to avoid this problem.

I would like the provider to honor the following environmental variables:

- INWX_USERNAME
- INWX_PASSWORD
- INWX_TAN
- INWX_API_URL

**Comment by scy** [comment]
@fsoederhuyzen Thanks for merging this, but you forgot to tag a new release :cry:
