### ISSUE TITLE
docs: add documentation for resource_dnssec_key

### ISSUE THREAD

**Issue by MeneDev** [inwx/terraform-provider-inwx#9]
Allow managing DNSSEC. For this setting the DNSKEY etc should be possible

**Comment by fsoederhuyzen** [comment]
It is possible to set the DNSKEY with [`resource_dnssec_key`](https://github.com/inwx/terraform-provider-inwx/blob/main/inwx/internal/resource/resource_dnssec_key.go) which has been merged in #1 since 1.1.0 but not been documented yet.

**Comment by MeneDev** [comment]
Thanks, I didn't realize it because I only looked at the docs. Works fine 😊
